export const CREATE_NEW_GAME = 'CREATE_NEW_GAME';
export const UPDATE_CHAR_TO_WORD_TILE_ROW = 'UPDATE_CHAR_TO_WORD_TILE_ROW';
export const MOVE_TO_NEXT_ROW = 'MOVE_TO_NEXT_ROW';
export const VERIFY_WORD_TILE_ROW = 'VERIFY_WORD_TILE_ROW';